language: cpp
sudo: required

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc

addons:
  apt:
    packages:
      - git
      - mercurial
before_script: 
  - sudo chmod +777 enviroment.bash
  - ./enviroment.bash

  - cd build
  - cmake ../src/

script:
- make -j4 